#!/bin/bash

echo "public extension Icon {" >> Material\ Icons.swift
echo "public struct Material {" >> Material\ Icons.swift
for categoryFolder in Material/*/; do

	folder=${categoryFolder#*/}
	folder=${folder%"/"}
	echo "public struct $folder {" >> Material\ Icons.swift
	for fileName in "$categoryFolder"*.png; do
		name=${fileName#$categoryFolder}
		extension="-48.png"
		noExtenion=${name%$extension}
		noSpaces=${noExtenion//-/_}
		echo "public static let ${noSpaces} = Icon.icon(\"$name\")" >> Material\ Icons.swift
	done
	echo "}" >> Material\ Icons.swift
done 
echo "}" >> Material\ Icons.swift
echo "}" >> Material\ Icons.swift
